App: #应用信息
  Name: jimoos-shop-server
  Author:
  Description: 积墨商城shop
  Addons:
    - Name: jm-ping
      Ref: jimo-public
      Group: base
      SourceType: git
      Source: 
      Description: 用于测试服务器是否可 ping
      Type: module
      DependOns: none
      Conflicts: none
      Migrations: migrations
      Docs: docs
